"""add cash calibration samples

Revision ID: 3f5e78aebe96
Revises: 5c148ac559d5
Create Date: 2026-09-20 16:07:38.688319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5e78aebe96'
down_revision: Union[str, None] = '5c148ac559d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_calibration_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denomination_cents', sa.Integer(), nullable=False),
    sa.Column('hue', sa.Float(), nullable=False),
    sa.Column('saturation', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('size_ratio', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_calibration_samples_denomination_cents'), 'cash_calibration_samples', ['denomination_cents'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_calibration_samples_denomination_cents'), table_name='cash_calibration_samples')
    op.drop_table('cash_calibration_samples')
    # ### end Alembic commands ###
